### PR TITLE
Item filtering and paging

### PR DESCRIPTION
**Pull request by akshar-raaj**
* Added pagination
* Added products pages filtered by category and company. Added pagination on these pages.
* Added a category page and linked it to product under that category.
skitch1
pagination
pagination-2
category-filter
company-filter

company-filter-and-pagination

categories

### CODE REVIEW

**Comment by akshar-raaj** [comment]
@pratu16x7 @rmehta Added pagination, category and company pages. Can you please review.

**Comment by pratu16x7** [comment]
A few clarifications:

- Nice use of params to solve the route problem. Any visual cue on the page for the current/active pagination and categories?
- Full page view of subsequent paginated pages and company page?

**Comment by akshar-raaj** [comment]
screencapture-my-third-8003-item-listing-2018-07-12-16_50_07
screencapture-my-third-8003-company-products-2018-07-12-17_17_48


Added full page view of paginated featured and category pages. Right now pagination only has "Previous", "<page_number>" and "Next". I will make it better to have a range, something like `Previous 1 3 5...Next`.

**Comment by akshar-raaj** [comment]
@pratu16x7 Added visual cue for category. Showing the category in `<h1>` and lead.
screencapture-my-third-8003-category-products-2018-07-12-16_55_14

**Review by pratu16x7 — APPROVED** [review]

**Pull request merged**
